# https://hub.docker.com/r/bitnami/openldap
networks:
  my-network:
    driver: bridge
services:
  openldap:
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
      - 3389:3389/tcp
      - 3389:3389/udp
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    networks:
      - my-network
    volumes:
      - 'openldap_data:/bitnami/openldap'
  # myapp:
  #   image: 'YOUR_APPLICATION_IMAGE'
  #   networks:
  #     - my-network
volumes:
  openldap_data:
    driver: local

