services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000 # API
      - 9001:9001 # WebUI
    volumes:
      - .minio-storage:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minioroot
    command: server --console-address ":9001" /data/

